# *Setup*

In [1]:
%load_ext autoreload
%autoreload 2

In [58]:
%%time
import numpy as np
import pandas as pd

from hid_avan.Thiessen import thiessen

CPU times: total: 0 ns
Wall time: 0 ns


In [40]:
def head_tail_info(df:pd.DataFrame, n:int=5):
    display(pd.concat((df.head(n), df.tail(n))), df.info())

def extract_daily_pr_array_from_funceme_dataset(funceme_txt_path, date_start, date_end, missing_pr=-999.):
    complete_array = np.loadtxt(funceme_txt_path)
    pr_array = complete_array[:, 3:]
    pr_array_w_missing = np.where(pr_array == missing_pr, np.nan, pr_array)

    date_column = np.reshape(pd.date_range(start=date_start, end=date_end, freq='D'), (-1, 1))
    
    pr_array

#def load_funceme_precipitation(missing_pr=-999.

In [ ]:
{'id':2173,
 'coord':[-40.4797, -5.4164],
 'pr_daily':[]}

In [60]:
pd.DataFrame({2173:[[-40.47, -5.41], [0., 0., 1., 2., 2., 3., 4., 5.,]],
36366:[[-40.47, -5.41], [0., 0., 1., 2., 2., 3., 4., 5.,]]})

,2173,36366
0,"[-40.47, -5.41]","[-40.47, -5.41]"
1,"[0.0, 0.0, 1.0, 2.0, 2.0, 3.0, 4.0, 5.0]","[0.0, 0.0, 1.0, 2.0, 2.0, 3.0, 4.0, 5.0]"


In [67]:
x_w_nan[:, 0]

array([ 2173., 36366.,  2174., 24012., 24019., 24030., 24037., 24078.,
       24095., 24150., 24151., 24165., 24167., 24169., 24187., 24190.,
       24206., 24233., 24235., 24265., 24313., 24315., 24330., 24455.,
       24456., 24505., 24506., 24510., 24511., 24512., 24552., 24553.,
       24554., 24555., 24556., 24557., 24558., 24559., 24578., 24579.,
       24580., 24581., 24582., 24585., 24586., 24587., 24588., 24589.,
       24590., 24591., 24592., 24598., 24601., 24620., 24629., 24633.,
       24648., 24651., 24724., 24740., 36620., 36625., 36629., 36649.,
       36658.,    61.,    70.,   146.,   532.])

In [80]:
np.reshape(pd.date_range(start='1973-01-01', end='2026-07-31', freq='D'), (-1, 1))

array([['1973-01-01T00:00:00.000000'],
       ['1973-01-02T00:00:00.000000'],
       ['1973-01-03T00:00:00.000000'],
       ...,
       ['2026-07-29T00:00:00.000000'],
       ['2026-07-30T00:00:00.000000'],
       ['2026-07-31T00:00:00.000000']],
      shape=(19570, 1), dtype='datetime64[us]')

In [72]:
help(pd.date_range)

Help on function date_range in module pandas:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize: 'bool' = False, name: 'Hashable | None' = None, inclusive: 'IntervalClosedType' = 'both', *, unit: 'TimeUnit | None' = None, **kwargs) -> 'DatetimeIndex'
    Return a fixed frequency DatetimeIndex.
    
    Returns the range of equally spaced time points (where the difference between any
    two adjacent points is specified by the given frequency) such that they fall in the
    range `[start, end]` , where the first one and the last one are, resp., the first
    and last time points in that range that fall on the boundary of ``freq`` (if given
    as a frequency string) or that are valid for ``freq`` (if given as a
    :class:`pandas.tseries.offsets.DateOffset`). If ``freq`` is positive, the points
    satisfy `start <[=] x <[=] end`, and if ``freq`` is negative, the points satisfy
    `end <[=] x <[=] start`. (If exactly one of ``start``, ``end``, or ``freq`` is

In [71]:
x_w_nan[:, 3:].T

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan,  0., nan],
       [nan, nan, nan, ..., nan,  0., nan],
       ...,
       [nan,  0.,  0., ...,  0., nan, nan],
       [nan,  0.,  0., ...,  0., nan, nan],
       [nan,  0.,  0., ...,  0., nan, nan]], shape=(19570, 69))

In [68]:
x_w_nan[:, [1, 2]]

array([[-40.4797  ,  -5.4164  ],
       [-40.9108  ,  -4.4156  ],
       [-41.1567  ,  -5.0586  ],
       [-40.941556,  -4.164583],
       [-40.678556,  -5.175361],
       [-40.748222,  -4.161083],
       [-40.312361,  -5.393778],
       [-40.766694,  -5.533   ],
       [-40.923889,  -4.744889],
       [-40.700917,  -5.719417],
       [-40.75    ,  -6.05    ],
       [-40.477639,  -5.412389],
       [-40.348639,  -5.69325 ],
       [-40.412778,  -5.14675 ],
       [-40.853167,  -5.433417],
       [-40.292222,  -5.063333],
       [-40.719389,  -5.116778],
       [-40.735833,  -4.700278],
       [-41.083333,  -4.95    ],
       [-40.533333,  -4.933333],
       [-40.761611,  -4.903861],
       [-40.70675 ,  -5.905833],
       [-40.922611,  -5.04925 ],
       [-40.909306,  -4.426944],
       [-40.703917,  -5.212   ],
       [-40.827944,  -4.750111],
       [-40.950556,  -4.136111],
       [-40.833306,  -4.283   ],
       [-41.063528,  -4.382278],
       [-40.676389,  -5.905833],
       [-4

In [65]:
x = np.loadtxt('../data/raw/pr_daily_funceme_34750000_19730101_20260731.txt')
x_w_nan = np.where(x==-999., np.nan, x)
#pd.DataFrame(x_w_nan)
#pd.DataFrame(x)

In [41]:
df = pd.read_csv('../data/raw/34750000.txt', header=None)
head_tail_info(df, 5)

<class 'pandas.DataFrame'>
RangeIndex: 8090 entries, 0 to 8089
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       8090 non-null   float64
 1   1       8090 non-null   float64
dtypes: float64(2)
memory usage: 126.5 KB


,0,1
0,-40.814582,-4.626249
1,-40.813749,-4.626249
2,-40.813749,-4.627083
3,-40.814582,-4.627083
4,-40.814582,-4.627916
8085,-40.812916,-4.623749
8086,-40.813749,-4.623749
8087,-40.813749,-4.624583
8088,-40.814582,-4.624583
8089,-40.814582,-4.626249


None

In [39]:
df = pd.read_excel('../data/raw/34750000_Vazoes.xlsx', parse_dates=['Data'])
head_tail_info(df, 5)

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Data    694 non-null    datetime64[us]
 1   Media   691 non-null    float64       
dtypes: datetime64[us](1), float64(1)
memory usage: 11.0 KB


,Data,Media
0,1964-02-01,NaN
1,1964-03-01,279.9676
2,1964-04-01,502.0310
3,1964-05-01,213.3629
4,1964-06-01,25.9365
689,2021-08-01,0.0200
690,2021-09-01,0.0000
691,2021-10-01,0.0000
692,2021-11-01,4.4730
693,2021-12-01,1.3916


None